# Properties
site_name: 'Boundless2D'
site_description: '2D Game Engine developed for YouTube'
site_author: 'Ludwig Fuechsl'
copyright: >-
  &copy; Copyright 2023 by Ludwig F&uuml;chsl

repo_name: 'Ohjurot/Boundless2D'
repo_url: 'https://github.com/Ohjurot/Boundless2D'
docs_dir: 'www'

# Navigation
nav:
  - Home: index.md

# Theme customization
theme:
  name: 'material'
  icon:
    logo: 'material/code-tags-check'
  palette: 
    # Light mode
    - scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    # Navigation
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top

  markdown_extensions:
    #admonition
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # Diagramms
    - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
    # Tasklist
    - pymdownx.tasklist:
      custom_checkbox: true
    # Footnotes
    - footnotes

# Cookies
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
